### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Zamir7** [1vanK/Urho3D_DotNetBindings#3]
Привет Иван, вы с CodingMonkey давно не были в сети, в гите н-ер, все норм?, выйди на связь плиз...

**Comment by 1vanK** [comment]
да все норм

**Comment by Zamir7** [comment]
Не буду оригинален) нужна помощь, в вопросе шейдеров... мы с GLoom делаем редактор шейдеров https://discourse.urho3d.io/t/node-based-material-editor/4326/12, и застряли уже ближе к бета выпуску, на некоторых моментах(
Как со временем и желанием?

**Comment by Zamir7** [comment]
крайне были бы благодарны, если бы ты присоединился к нам как соавтор. Грязная работа позади, нам немного консультации бы в вопросах шейдера...

**Comment by 1vanK** [comment]
конечно помогу, а какой вопрос?

**Comment by Zamir7** [comment]
Там скорее вопросы чем вопрос: проблема организации Direct Shadow, не умение организовать "честный" фон в refractionColor, в прозрачном объекте. Проблема с normalMap..

Ты есть на discord? или в трелло хотя бы...

**Comment by 1vanK** [comment]
не, нету

я могу на конкретные вопросы ответить если что, изучать ваш проект целиком нету времени

**Comment by Zamir7** [comment]
Ок, спасибо на том! Эмм, скоро сформулирую.. если получится в разрыве от проекта задать вопрос

**Comment by Zamir7** [comment]
Привет Иван, как то сами разрулили вопросы, открыли бету... Вдруг если заинтересует вот репа
https://github.com/gleblebedev/Urho3DMaterialGraphEditor

**Comment by 1vanK** [comment]
Круто! А циклы можно делать? Я как-то с нодами баловался и если граф однонаправленный, то все  просто, а циклы стали проблемой

**Comment by Zamir7** [comment]
циклы ты про  for (i = 1; ... ?  в этом случае - нет,
или цикличность связи? цикличность отлавливается на уровне потягивания пина и исключаются из возможных к подключению... сложность в отлавливании?

**Comment by 1vanK** [comment]
ну да, циклы for, while и ветвления, они бывает в шейдерах нужны

**Comment by Zamir7** [comment]
пока не понадобились, да и тема настолько геморная, что лучше не лезть пока все робит)

**Comment by Zamir7** [comment]
Смотрел вчера на андроиде  шейдер с envCubMap, результат превзошел все мои ожидания, 120 FPS! Ложит на обе лопатки, любой урховский шейдер - это фантастика!

**Comment by Zamir7** [comment]
Кстати, переход урхо на GL 3.0, какой кровью осуществимо?

**Comment by 1vanK** [comment]
урхо по умолчанию на gl 3 работает, gl 2.1 включается только если железка gl 3 не поддерживает

**Comment by Zamir7** [comment]
забыл уточнить,  я про андроид, там жестко gl 2

**Comment by 1vanK** [comment]
про андроид не шарю

**Comment by Zamir7** [comment]
Ах, да... вы же с СМ равнодушны к сабжу

**Comment by Zamir7** [comment]
Приходи к нам на дискорд, поболтаем как в старые добрые) Там CM (нашел таки его), Gloom, StepEver... Если нет времени, можно с телефона хотя бы выходить на связь. Как зарегишься напиши имя,я пришлю приглашение. Ждем!)

**Comment by 1vanK** [comment]
та не, всякие скайпы контактики дискорды в параллельной от меня вселенной находятся

**Comment by Zamir7** [comment]
хах, те за 50?)

**Comment by 1vanK** [comment]
Считаю бессмысленным тратить время на ерунду вроде выкладывания фоточек еды в инстаграмм

**Comment by Zamir7** [comment]
Хмм, меня ни разу нет в инста тоже, и в твитер и т.д., У нас профессиональное общение;) единомышленников... я живу в провинциальном городке, и вживую не видел прогерра, не то чтобы общаться(

**Comment by Zamir7** [comment]
Привет Иван, ты делаешь платформер? https://github.com/urho3d/Urho3D/issues/2390

**Comment by Zamir7** [comment]
а скрин откуда, если не секрет?

**Comment by 1vanK** [comment]
это же один из примеров в составе движка

**Comment by Zamir7** [comment]
Хмм, а в урхошарпе нет этого примера

**Comment by Zamir7** [comment]
оо, да там много чего нет оказывается)
